pipeline:
  name: postgres-to-null-5M

source:
  type: postgres
  config:
    host: pg
    port: 5432
    dbname: lab
    user: lab
    password: lab
    query: >
      SELECT e.*,
             (e.event_sequence + (g.n * 100000)) AS synthetic_sequence
      FROM spacecraft_telemetry_events e
      CROSS JOIN generate_series(0, 49) AS g(n)
    batch_size: 5000

destination:
  type: "null"
